ALTER TABLE `users`
ADD COLUMN `activity` int(1) DEFAULT NULL,
ADD COLUMN `dateOfLastAuth` DATETIME DEFAULT NULL,
ADD COLUMN `registrationDate` DATE DEFAULT NULL,
ADD COLUMN `nickname` VARCHAR(100) DEFAULT NULL;

