ALTER TABLE `users`
ADD COLUMN `active` int(1) DEFAULT NULL,
ADD COLUMN `ast_auth_date` DATETIME DEFAULT NULL,
ADD COLUMN `register_date` DATE DEFAULT NULL,
ADD COLUMN `nickname` VARCHAR(100) DEFAULT NULL;

